### ISSUE TITLE
Missing module 'oauth2client'

### ISSUE THREAD

**Issue by duelle** [itssimon/calendar-sync#2]
After following the README and running the command
> python ./calendar_sync.py

I got the following error
> ModuleNotFoundError: No module named 'oauth2client'

To have all dependencies in place, it was necessary to install the said module using
> pip install oauth2client

Maybe it would make sense to also add this to the installation instructions.

**Comment by itssimon** [comment]
Thanks, I added oauth2client to the requirements.txt
